healthcheck:
    path: /healthcheck
    controller: App\Infrastructure\HealthCheck\HealthCheckController

basket-check-multiple-payment-option:
    path: /basket/{uuidAsString}/check-multiple-payment-option
    controller: App\Infrastructure\Basket\BasketController::checkMultiplePaymentOption

basket-create-payment:
    path: /basket/{uuidAsString}/create-payment/{chosenInstallmentCount}
    controller: App\Infrastructure\Basket\BasketController::createPayment
