healthcheck:
    path: /healthcheck
    controller: App\Infrastructure\HealthCheck\HealthCheckController

basket-check-multiple-payment-option:
    path: /basket/{uuidAsString}/check-multiple-payment-option
    controller: App\Infrastructure\Basket\BasketController::checkMultiplePaymentOption
