services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    fake_payment_method:
        class: App\Tests\Behat\Basket\FakePaymentMethod

    App\Domain\Payment\PaymentMethod: '@fake_payment_method'

#    alma_payment_method:
#        class: App\Infrastructure\Payment\AlmaPaymentMethod
#        arguments:
#            - '@alma_client'
#            - '%env(PAYMENT_RETURN_URL)%'
#
#    App\Domain\Payment\PaymentMethod: '@alma_payment_method'
